FROM node:20-alpine AS production

WORKDIR /app

# Copy production dependencies and built output
COPY package.json package-lock.json ./
COPY ./dist ./dist
COPY ./node_modules ./node_modules

# Set environment
ENV NODE_ENV=production
ENV PORT=8081

EXPOSE 8081

CMD ["npm", "run", "start"]