FROM node:20-alpine AS production

WORKDIR /app

# Build and download node_modules
COPY package.json package-lock.json ./
RUN npm install

# Copy production dependencies and built output
COPY ./dist ./dist

# Set environment
ENV NODE_ENV=production
ENV PORT=8081

EXPOSE 8081

CMD ["npm", "run", "start"]