name: Build and Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install and Build
        run: |
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
          npm install
          npm run build:web

      - name: Clean up Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/localtaskapp
            rm -rf ./dist ./package.json ./package-lock.json ./docker-compose.yml ./Dockerfile.nginx ./Dockerfile.webapp ./nginx.conf

      - name: Copy files to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          source: "./dist,./package.json,./package-lock.json,./docker-compose.yml,./Dockerfile.nginx,./Dockerfile.webapp,./nginx.conf"
          target: "/home/ubuntu/localtaskapp"

      - name: Deploy on Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/localtaskapp
            sudo docker compose down -v --rmi all --remove-orphans
            sudo docker compose up -d --build
            sudo docker image prune -f
